export const RESPONSE_MESSAGE = {
  PASSWORD_AND_CONFIRM_PASSWORD_ARE_NOT_THE_SAME:
    'Password and confirm password are not the same.',
  REFRESH_TOKEN_NOT_FOUND: 'Refresh token not found.',
  INVALID_OR_EXPIRED_REFRESH_TOKEN: 'Invalid or expired refresh token',
  USER_NO_LONGER_EXISTS: 'User no longer exists',
  EMAIL_ALREADY_IN_USE: 'Email already in use',
  INVALID_CREDENTIALS: 'Invalid credentials',
  SUCCESSFULLY_LOGGED_OUT: 'Successfully logged out',
  NO_TOKEN_FOUND_IN_COOKIES: 'No token found in cookies',
  INVALID_TOKEN: 'Invalid token',
  CHAT_ROOM_DELETED_SUCCESSFULLY: 'Chat room deleted successfully',
  CHAT_ROOM_ALREADY_EXISTS: 'Chat room already exists',
  CHAT_ROOM_DO_NOT_EXIST: 'Chat room do not exist',
  EMAIL_IS_REQUIRED: 'Email is required.',
  EMAIL_MUST_BE_VALID: 'Email must be valid.',
  PASSWORD_IS_REQUIRED: 'Password is required.',
  FULLNAME_IS_REQUIRED: 'Fullname is required.',
  FULLNAME_MUST_BE_A_STRING: 'Fullname must be a string.',
  PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS:
    'Password must be at least 8 characters.',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm Password is required.',
  NAME_IS_REQUIRED: 'Name is required.',
  VALIDATION_ERROR: 'Validation error',
  VALIDATION_ERROR_CODE: 'VALIDATION_ERROR',
  BAD_REQUEST: 'Bad Request',
};
